/**
 * Comprehensive Cloud, ChatGPT, Google AI Studio, and GitHub
 * Integration Schemas and Configurations for all evonix Web Tools.
 *
 * Implements:
 * 1. OpenAI Custom GPT Action Schemas (OpenAPI 3.1.0)
 * 2. Google AI Studio Function Declarations (Gemini API format)
 * 3. GitHub Automation Workflows (.github/workflows)
 * 4. Cloud Sync / Webhook Payloads
 * 5. Dedicated "Top 5 Mobile App Tools" designation per user specification
 */

export interface ToolIntegrationDef {
  toolId: string;
  name: string;
  urduName: string;
  shortName: string;
  isMobileAppCore: boolean; // Flag for the 5 Core Mobile Application Tools
  mobileCoreOrder?: number;
  category: 'business-export' | 'ecommerce-growth' | 'diagnostics-lab';
  categoryLabel: string;
  summary: string;

  // ChatGPT Integration
  chatGptQuickPrompt: string;
  chatGptCustomGptInstructions: string;
  openApiSchema: object;

  // Google AI Studio (Gemini) Integration
  geminiFunctionDeclaration: object;
  geminiSystemInstruction: string;
  geminiPromptTemplate: string;

  // GitHub Integration
  githubWorkflowYaml: string;
  githubSchemaSpec: object;

  // Cloud Storage & Webhook
  cloudSamplePayload: object;
}

export const ALL_TOOL_INTEGRATIONS: Record<string, ToolIntegrationDef> = {
  invoice: {
    toolId: 'invoice',
    name: 'Global Micro-Invoice Generator',
    urduName: 'گلوبل مائیکرو انوائس جنریٹر',
    shortName: 'Invoice Maker',
    isMobileAppCore: true,
    mobileCoreOrder: 1,
    category: 'business-export',
    categoryLabel: 'Business & Export',
    summary: 'Zero-database client invoice generator with 100+ countries tax engine, live Code128 barcodes, and PDF export.',
    chatGptQuickPrompt: `You are an expert international trade and commercial invoicing specialist. Analyze and review the following commercial invoice generated by evonix Global Micro-Invoice Generator:
- Seller Location: Kolti Behram, Sialkot, Pakistan
- Invoice Number: INV-2026-0042
- Currency: USD
- Line Items: Surgical Grade Scalpel Handles ($2,400), Titanium Forceps ($3,800)
- Tax / VAT: Standard 0% Export Exemption
- Barcode Format: Code128 Auto

Please verify:
1. Harmonized System (HS) code compliance for European & US customs clearance.
2. Complete payment term clauses (Net 30, LC at Sight, TT Wire).
3. Recommended incoterms (FOB Karachi / Sialkot Dry Port, CIF Hamburg).`,
    chatGptCustomGptInstructions: `You are the evonix Global Commercial Invoice Assistant. When users request client invoices, use the createCommercialInvoice action. Always enforce export compliance, calculate item subtotals accurately, apply appropriate regional tax rates (GST, VAT, Sales Tax), and output structured invoice summaries with payment instructions.`,
    openApiSchema: {
      openapi: '3.1.0',
      info: {
        title: 'evonix Global Micro-Invoice API',
        version: '1.0.0',
        description: 'Create zero-database commercial invoices with international tax compliance and Code128 barcode generation.',
      },
      servers: [
        {
          url: 'https://evonixtech.com/api/v1',
          description: 'Production evonix Cloud Gateway',
        },
      ],
      paths: {
        '/invoices/generate': {
          post: {
            operationId: 'createCommercialInvoice',
            summary: 'Generate compliant commercial invoice schema',
            requestBody: {
              required: true,
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    required: ['invoiceNumber', 'clientName', 'items', 'currency'],
                    properties: {
                      invoiceNumber: { type: 'string', example: 'INV-2026-0089' },
                      issueDate: { type: 'string', format: 'date', example: '2026-10-06' },
                      clientName: { type: 'string', example: 'Apex Surgical Imports LLC' },
                      clientEmail: { type: 'string', format: 'email', example: 'procurement@apexsurgical.com' },
                      currency: { type: 'string', enum: ['USD', 'EUR', 'GBP', 'PKR', 'AED'], example: 'USD' },
                      taxRatePercentage: { type: 'number', example: 0 },
                      items: {
                        type: 'array',
                        items: {
                          type: 'object',
                          required: ['description', 'quantity', 'unitPrice'],
                          properties: {
                            description: { type: 'string', example: 'Surgical Retractors SS316' },
                            quantity: { type: 'integer', example: 50 },
                            unitPrice: { type: 'number', example: 45.0 },
                          },
                        },
                      },
                    },
                  },
                },
              },
            },
            responses: {
              '200': {
                description: 'Invoice successfully computed and validated',
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      properties: {
                        subtotal: { type: 'number' },
                        taxAmount: { type: 'number' },
                        grandTotal: { type: 'number' },
                        barcodeString: { type: 'string' },
                        pdfDownloadUrl: { type: 'string' },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    geminiFunctionDeclaration: {
      name: 'generateGlobalInvoice',
      description: 'Generates an ISO-compliant commercial export invoice with multi-currency taxes and Code128 barcode check.',
      parameters: {
        type: 'OBJECT',
        properties: {
          invoiceNumber: { type: 'STRING', description: 'Unique invoice identification code' },
          buyerName: { type: 'STRING', description: 'Buyer organization or individual name' },
          currency: { type: 'STRING', description: 'ISO 4217 Currency Code (USD, EUR, GBP, PKR, AED)' },
          items: {
            type: 'ARRAY',
            items: {
              type: 'OBJECT',
              properties: {
                name: { type: 'STRING' },
                quantity: { type: 'NUMBER' },
                rate: { type: 'NUMBER' },
              },
              required: ['name', 'quantity', 'rate'],
            },
          },
          taxPercent: { type: 'NUMBER', description: 'Applicable GST/VAT or sales tax rate' },
        },
        required: ['invoiceNumber', 'buyerName', 'currency', 'items'],
      },
    },
    geminiSystemInstruction: `You are the Google AI Studio Gemini Enterprise Invoice Engine. Calculate accurate commercial invoice totals, apply international trade taxes, provide Code128 encoding strings, and generate executive financial breakdowns for cross-border B2B transactions originating from Sialkot industrial exporters.`,
    geminiPromptTemplate: `Evaluate the following invoice draft:\nInvoice #: {{invoiceNumber}}\nClient: {{clientName}}\nItems: {{itemsList}}\nCalculate final payable sum, advise on export tax exemption under Sialkot Chamber of Commerce trade provisions, and return formatted Markdown.`,
    githubWorkflowYaml: `name: evonix Invoice Generator Automation
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      invoice_id:
        description: 'Invoice Identifier'
        required: true
        default: 'INV-2026-0001'

jobs:
  validate-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Validate Invoice JSON Schema
        run: |
          npm ci
          npx ajv-cli validate -s ./schemas/invoice-schema.json -d ./data/invoices/*.json
      - name: Compile PDF Artifact
        run: echo "Invoice compiled successfully for \${{ inputs.invoice_id }}"`,
    githubSchemaSpec: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      title: 'evonixInvoiceSchema',
      type: 'object',
      required: ['invoiceNumber', 'currency', 'subtotal', 'grandTotal'],
      properties: {
        invoiceNumber: { type: 'string' },
        currency: { type: 'string', enum: ['USD', 'EUR', 'GBP', 'PKR', 'AED'] },
        subtotal: { type: 'number' },
        grandTotal: { type: 'number' },
      },
    },
    cloudSamplePayload: {
      provider: 'evonix-cloud-sync',
      tool: 'invoice',
      version: '2026.1',
      lastSynced: new Date().toISOString(),
      state: {
        invoiceNumber: 'INV-2026-0042',
        clientName: 'Apex Surgical Imports LLC',
        currency: 'USD',
        taxPercent: 0,
        itemsCount: 2,
        grandTotal: 6200.0,
      },
    },
  },

  'ecommerce-calculator': {
    toolId: 'ecommerce-calculator',
    name: 'E-Commerce Margin & COD Simulator',
    urduName: 'ای کامرس بی ٹو بی مارجن کیلکولیٹر',
    shortName: 'E-Com Margin Calc',
    isMobileAppCore: true,
    mobileCoreOrder: 2,
    category: 'ecommerce-growth',
    categoryLabel: 'E-Commerce & Ads',
    summary: 'Calculate net profit margins, ad spend ROAS, multi-courier COD fees, and return loss simulations for Pakistani & global e-commerce.',
    chatGptQuickPrompt: `Analyze the following Pakistani E-Commerce unit economics:
- Product Selling Price: PKR 4,500
- Product Sourcing Cost: PKR 1,600
- Ad Spend per Acquisition (CAC): PKR 1,100
- Courier Delivery Fee (TCS / Leopards): PKR 280
- Cash-on-Delivery (COD) Commission: 3.5%
- Return-to-Origin (RTO) Rate: 18%
- Reverse Freight Penalty: PKR 180 per returned package

Please calculate:
1. True net contribution margin per delivered parcel.
2. Breakeven ROAS required on Meta / TikTok Ads.
3. Monthly net profit if shipping 1,500 orders per month.
4. Top 3 strategies to decrease RTO from 18% down to 9% in Sialkot, Lahore, and Karachi.`,
    chatGptCustomGptInstructions: `You are the evonix E-Commerce Profitability & COD Consultant. Help store owners analyze their real margins after factoring in hidden costs like return delivery charges, courier COD collection commissions, dead stock, and packaging damage.`,
    openApiSchema: {
      openapi: '3.1.0',
      info: {
        title: 'evonix E-Commerce Margin Simulator API',
        version: '1.0.0',
        description: 'Simulate e-commerce unit economics with COD tariffs and RTO loss models.',
      },
      paths: {
        '/ecom/simulate-margin': {
          post: {
            operationId: 'simulateEcomMargins',
            summary: 'Calculate net profit and breakeven ROAS',
            requestBody: {
              required: true,
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    required: ['salePrice', 'productCost', 'adCost', 'shippingFee', 'rtoPercent'],
                    properties: {
                      salePrice: { type: 'number', example: 4500 },
                      productCost: { type: 'number', example: 1600 },
                      adCost: { type: 'number', example: 1100 },
                      shippingFee: { type: 'number', example: 280 },
                      codPercent: { type: 'number', example: 3.5 },
                      rtoPercent: { type: 'number', example: 18 },
                    },
                  },
                },
              },
            },
            responses: {
              '200': {
                description: 'Simulation results',
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      properties: {
                        netProfitPerOrder: { type: 'number' },
                        netMarginPercentage: { type: 'number' },
                        breakevenRoas: { type: 'number' },
                        monthlyNetProjection: { type: 'number' },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    geminiFunctionDeclaration: {
      name: 'calculateEcomProfitability',
      description: 'Calculates net e-commerce profitability including COD courier fees, ad ROAS, and return damage.',
      parameters: {
        type: 'OBJECT',
        properties: {
          sellingPrice: { type: 'NUMBER' },
          cogs: { type: 'NUMBER' },
          adSpendPerOrder: { type: 'NUMBER' },
          deliveryCost: { type: 'NUMBER' },
          rtoRatePercent: { type: 'NUMBER' },
          courierCodFeeRate: { type: 'NUMBER' },
        },
        required: ['sellingPrice', 'cogs', 'adSpendPerOrder', 'deliveryCost', 'rtoRatePercent'],
      },
    },
    geminiSystemInstruction: `You are the Google AI Studio Gemini E-Commerce Optimizer for evonix. Model multi-courier cash flows, recommend ROAS targets, and simulate margin sensitivity across Pakistani logistics corridors.`,
    geminiPromptTemplate: `Perform unit economics breakdown for Retail Price: {{sellingPrice}} PKR, Sourcing: {{cogs}} PKR, Ad Cost: {{adCost}} PKR, RTO: {{rtoPercent}}%. Provide actionable recommendations.`,
    githubWorkflowYaml: `name: E-Commerce Margin Simulator Benchmark
on:
  schedule:
    - cron: '0 6 * * 1'
  workflow_dispatch:

jobs:
  run-margin-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Ecom Profit Unit Tests
        run: echo "Testing COD & RTO algorithms..."`,
    githubSchemaSpec: {
      title: 'EcomMarginModel',
      type: 'object',
      properties: {
        sellingPrice: { type: 'number' },
        netProfit: { type: 'number' },
        breakevenRoas: { type: 'number' },
      },
    },
    cloudSamplePayload: {
      provider: 'evonix-cloud-sync',
      tool: 'ecommerce-calculator',
      version: '2026.1',
      lastSynced: new Date().toISOString(),
      state: {
        salePrice: 4500,
        productCost: 1600,
        adCost: 1100,
        rtoPercent: 18,
        netProfit: 865,
        breakevenRoas: 2.34,
      },
    },
  },

  'cbm-calculator': {
    toolId: 'cbm-calculator',
    name: 'B2B Industrial CBM & Freight Engine',
    urduName: 'بی ٹو بی انڈسٹریل CBM کارٹن و فریٹ کیلکولیٹر',
    shortName: 'CBM Cargo Engine',
    isMobileAppCore: true,
    mobileCoreOrder: 3,
    category: 'business-export',
    categoryLabel: 'Business & Export',
    summary: 'Compute carton volume in CBM, air volumetric weight, and 20ft/40ft/40HQ container stuffing capacity instantly.',
    chatGptQuickPrompt: `Act as a senior international sea and air freight forwarder. Analyze the following shipment parameters from Sialkot Dry Port to Hamburg Port:
- Total Master Cartons: 150 cartons
- Carton Dimensions: Length 60 cm, Width 40 cm, Height 35 cm
- Gross Weight per Carton: 18.5 kg
- Packaging Content: Surgical Instruments in foam inserts

Please calculate:
1. Total Volume in Cubic Meters (m³ / CBM).
2. Total Gross Weight vs Air Volumetric Weight (using 1:5000 and 1:6000 divisors).
3. Container stuffing capacity: percentage filled in a 20ft General Purpose (GP) container (33 CBM limit) and a 40ft High Cube (76 CBM limit).
4. Estimated ocean freight charge if rate is $85 per CBM.`,
    chatGptCustomGptInstructions: `You are the evonix B2B Logistics and CBM Calculation Assistant. Always determine volumetric weights accurately, verify container stuffing efficiency, and warn users if their shipment exceeds maximum road axle or container weight limits.`,
    openApiSchema: {
      openapi: '3.1.0',
      info: {
        title: 'evonix B2B CBM & Logistics Engine API',
        version: '1.0.0',
        description: 'Calculate cargo volumetric measurements, carton packaging, and container capacities.',
      },
      paths: {
        '/logistics/cbm-calculator': {
          post: {
            operationId: 'calculateFreightCbm',
            summary: 'Calculate total CBM and volumetric weight',
            requestBody: {
              required: true,
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    required: ['lengthCm', 'widthCm', 'heightCm', 'quantity', 'weightKgPerCarton'],
                    properties: {
                      lengthCm: { type: 'number', example: 60 },
                      widthCm: { type: 'number', example: 40 },
                      heightCm: { type: 'number', example: 35 },
                      quantity: { type: 'integer', example: 150 },
                      weightKgPerCarton: { type: 'number', example: 18.5 },
                    },
                  },
                },
              },
            },
            responses: {
              '200': {
                description: 'Freight computation details',
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      properties: {
                        totalCbm: { type: 'number' },
                        totalGrossWeightKg: { type: 'number' },
                        airVolumetricWeightKg: { type: 'number' },
                        container20ftPercent: { type: 'number' },
                        container40hqPercent: { type: 'number' },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    geminiFunctionDeclaration: {
      name: 'calculateCargoCbm',
      description: 'Calculates cargo Cubic Meters (CBM), air chargeable weight, and container volume utilization.',
      parameters: {
        type: 'OBJECT',
        properties: {
          cartonCount: { type: 'NUMBER' },
          lengthCm: { type: 'NUMBER' },
          widthCm: { type: 'NUMBER' },
          heightCm: { type: 'NUMBER' },
          grossWeightKg: { type: 'NUMBER' },
        },
        required: ['cartonCount', 'lengthCm', 'widthCm', 'heightCm'],
      },
    },
    geminiSystemInstruction: `You are the Google AI Studio Gemini Industrial Cargo Specialist for evonix. Evaluate export cargo stowage from Pakistan, calculate ocean and air freight chargeable metrics, and formulate optimal palletization schemas.`,
    geminiPromptTemplate: `Compute export shipment for {{cartonCount}} cartons ({{length}}x{{width}}x{{height}} cm), {{grossWeight}} kg total. Detail container filling and chargeable freight metrics.`,
    githubWorkflowYaml: `name: evonix CBM Engine Continuous Verification
on: [push, pull_request]
jobs:
  verify-calculations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify CBM Formula Math
        run: echo "Verifying CBM math: 60*40*35/1000000 = 0.084 CBM per carton"`,
    githubSchemaSpec: {
      title: 'CbmLogisticsSpec',
      type: 'object',
      properties: {
        cartonDimensions: { type: 'string' },
        totalCbm: { type: 'number' },
        containerType: { type: 'string' },
      },
    },
    cloudSamplePayload: {
      provider: 'evonix-cloud-sync',
      tool: 'cbm-calculator',
      version: '2026.1',
      lastSynced: new Date().toISOString(),
      state: {
        cartons: 150,
        dimensions: { length: 60, width: 40, height: 35 },
        totalCbm: 12.6,
        grossWeightKg: 2775,
        container20ftFillPercent: 38.18,
      },
    },
  },

  'developer-cost-calculator': {
    toolId: 'developer-cost-calculator',
    name: 'Dedicated Developer Cost Calculator',
    urduName: 'ڈیڈیکیٹڈ ڈویلپر کاسٹ کیلکولیٹر',
    shortName: 'Developer Rates',
    isMobileAppCore: true,
    mobileCoreOrder: 4,
    category: 'business-export',
    categoryLabel: 'Business & Export',
    summary: 'Compare USA, UK & UAE developer salaries against dedicated offshore engineers with instant savings summary.',
    chatGptQuickPrompt: `You are an IT workforce budgeting and global offshore software development consultant. Review this cost comparison:
- Benchmark In-House Location: New York / Silicon Valley, USA ($135,000 / year base salary per Full-Stack Engineer + $35,000 benefits/payroll tax = $170,000 total burden)
- Dedicated Team Configuration: 2 Senior Full-Stack Engineers, 1 React/Next.js Frontend Engineer, 1 DevOps Engineer (Total team: 4 engineers)
- evonix Dedicated Engineer Monthly Retainer: $2,200 / month ($26,400 / year per engineer)

Please provide:
1. Executive Capital Savings summary (monthly and annual dollar savings).
2. Return on Investment (ROI) and team scaling timeline.
3. Quality assurance and IP ownership assurances for European and North American enterprises partnering with evonix technologies in Sialkot, Pakistan.`,
    chatGptCustomGptInstructions: `You are the evonix Dedicated Engineering Talent Advisor. Help CTOs, founders, and technical directors compute their exact offshore cost advantage, evaluate skills, and structure dedicated developer teams.`,
    openApiSchema: {
      openapi: '3.1.0',
      info: {
        title: 'evonix Developer Rate Comparison API',
        version: '1.0.0',
        description: 'Calculate international software engineer salary differentials and offshore team savings.',
      },
      paths: {
        '/rates/compare-developer-cost': {
          post: {
            operationId: 'compareDeveloperCosts',
            summary: 'Compare local vs offshore developer costs',
            requestBody: {
              required: true,
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    required: ['region', 'teamSize', 'seniorityLevel'],
                    properties: {
                      region: { type: 'string', enum: ['USA', 'UK', 'UAE', 'Australia', 'Germany'], example: 'USA' },
                      teamSize: { type: 'integer', example: 4 },
                      seniorityLevel: { type: 'string', enum: ['Junior', 'Mid-Level', 'Senior', 'Tech Lead'], example: 'Senior' },
                    },
                  },
                },
              },
            },
            responses: {
              '200': {
                description: 'Comparison analysis',
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      properties: {
                        inHouseAnnualCost: { type: 'number' },
                        evonixAnnualCost: { type: 'number' },
                        netAnnualSavings: { type: 'number' },
                        savingsPercentage: { type: 'number' },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    geminiFunctionDeclaration: {
      name: 'calculateDevCostSavings',
      description: 'Calculates hiring cost differences between Western markets and dedicated evonix offshore development teams.',
      parameters: {
        type: 'OBJECT',
        properties: {
          clientCountry: { type: 'STRING', description: 'USA, UK, UAE, Australia, Germany, or Canada' },
          engineersCount: { type: 'NUMBER', description: 'Number of developers' },
          experienceTier: { type: 'STRING', description: 'Junior, Mid-Level, Senior, or Lead' },
        },
        required: ['clientCountry', 'engineersCount', 'experienceTier'],
      },
    },
    geminiSystemInstruction: `You are the Google AI Studio Gemini Offshore Engineering Workforce Analyst for evonix. Contrast corporate tech hiring burdens against dedicated offshore staffing, demonstrating verified cost reductions of up to 72% with complete IP security.`,
    geminiPromptTemplate: `Compare cost for {{engineersCount}} {{experienceTier}} developers in {{clientCountry}} vs dedicated evonix engineers. Present breakdown in tabular Markdown with annual savings.`,
    githubWorkflowYaml: `name: Developer Cost Rate Sync
on:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  update-salary-indices:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Global Tech Salary Index
        run: echo "Updating Q4 international developer wage indices..."`,
    githubSchemaSpec: {
      title: 'DevCostComparison',
      type: 'object',
      properties: {
        region: { type: 'string' },
        netAnnualSavings: { type: 'number' },
        savingsPercentage: { type: 'number' },
      },
    },
    cloudSamplePayload: {
      provider: 'evonix-cloud-sync',
      tool: 'developer-cost-calculator',
      version: '2026.1',
      lastSynced: new Date().toISOString(),
      state: {
        region: 'USA',
        teamSize: 4,
        seniority: 'Senior',
        inHouseAnnualCost: 680000,
        evonixAnnualCost: 105600,
        netAnnualSavings: 574400,
        savingsPercent: 84.4,
      },
    },
  },

  'ai-visibility-checker': {
    toolId: 'ai-visibility-checker',
    name: 'AI Visibility & E-E-A-T Checker',
    urduName: 'اے آئی اویلیبلٹی ای ای اے ٹی چیکر',
    shortName: 'AI Visibility Audit',
    isMobileAppCore: true,
    mobileCoreOrder: 5,
    category: 'ecommerce-growth',
    categoryLabel: 'Growth & SEO',
    summary: 'Client-side audit for ChatGPT, Claude, and Google AI Overviews visibility readiness & entity schema.',
    chatGptQuickPrompt: `You are a Generative Engine Optimization (GEO) and E-E-A-T auditor. Evaluate the following website entity parameters:
- Brand Entity: evonix technologies
- Physical Head Office: Kolti Behram, Sialkot, Pakistan
- Service Scope: Chip-Level Laptop Repair, Thermal Printer Troubleshooting, B2B Web Application Development
- Organization Schema (@type: Organization / LocalBusiness): Active with geo-coordinates, areaServed, knowsAbout
- Author & Expert Credentials: Documented certified technicians, real hardware bench photography, customer reviews

Please review:
1. Retrieval-Augmented Generation (RAG) citation readiness for ChatGPT, Perplexity, and Google AI Overviews.
2. E-E-A-T signal strengths (Experience, Expertise, Authoritativeness, Trustworthiness).
3. Recommended JSON-LD structured data improvements to capture the #1 citation spot in AI answers.`,
    chatGptCustomGptInstructions: `You are the evonix AI Search & GEO Auditor. Assess websites for their ability to be referenced and cited accurately by LLMs like ChatGPT, Claude, and Gemini. Identify missing structured data, ambiguous entity claims, and content gaps.`,
    openApiSchema: {
      openapi: '3.1.0',
      info: {
        title: 'evonix AI Visibility & GEO Audit API',
        version: '1.0.0',
        description: 'Audit domain readiness for citation in ChatGPT, Claude, Perplexity, and Google AI Overviews.',
      },
      paths: {
        '/seo/ai-visibility-audit': {
          post: {
            operationId: 'auditAiVisibility',
            summary: 'Audit E-E-A-T and LLM citation potential',
            requestBody: {
              required: true,
              content: {
                'application/json': {
                  schema: {
                    type: 'object',
                    required: ['url', 'brandName'],
                    properties: {
                      url: { type: 'string', format: 'uri', example: 'https://evonixtech.com' },
                      brandName: { type: 'string', example: 'evonix technologies' },
                      primaryIndustry: { type: 'string', example: 'IT & Hardware Engineering' },
                    },
                  },
                },
              },
            },
            responses: {
              '200': {
                description: 'GEO Audit report',
                content: {
                  'application/json': {
                    schema: {
                      type: 'object',
                      properties: {
                        overallGeoScore: { type: 'number' },
                        eeatRating: { type: 'string' },
                        schemaCompletenessPercent: { type: 'number' },
                        recommendations: { type: 'array', items: { type: 'string' } },
                      },
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
    geminiFunctionDeclaration: {
      name: 'auditWebsiteEeatAndGeo',
      description: 'Audits domain readiness for generative AI citation and Google E-E-A-T compliance.',
      parameters: {
        type: 'OBJECT',
        properties: {
          domainUrl: { type: 'STRING' },
          businessEntityName: { type: 'STRING' },
          targetKeywords: { type: 'ARRAY', items: { type: 'STRING' } },
        },
        required: ['domainUrl', 'businessEntityName'],
      },
    },
    geminiSystemInstruction: `You are the Google AI Studio Gemini GEO Specialist for evonix. Evaluate website entities, detect hallucination vulnerabilities in LLM answers, and recommend entity optimization tactics for Google AI Overviews and Search Grounding.`,
    geminiPromptTemplate: `Audit {{businessEntityName}} ({{domainUrl}}) for AI visibility readiness. Assess E-E-A-T signals, entity disambiguation, and suggest top 3 schema fixes.`,
    githubWorkflowYaml: `name: Daily AI Visibility & Schema Audit
on:
  schedule:
    - cron: '0 3 * * *'
jobs:
  audit-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Schema.org JSON-LD
        run: echo "Auditing live schema.org graph for evonixtech.com..."`,
    githubSchemaSpec: {
      title: 'AiVisibilityReport',
      type: 'object',
      properties: {
        domain: { type: 'string' },
        geoScore: { type: 'number' },
        eeatStatus: { type: 'string' },
      },
    },
    cloudSamplePayload: {
      provider: 'evonix-cloud-sync',
      tool: 'ai-visibility-checker',
      version: '2026.1',
      lastSynced: new Date().toISOString(),
      state: {
        domain: 'evonixtech.com',
        geoScore: 94,
        eeatStatus: 'High Authority',
        schemaStatus: 'Validated LocalBusiness + Organization Graph',
      },
    },
  },

  'export-barcode-studio': {
    toolId: 'export-barcode-studio',
    name: 'Export Barcode Label Studio',
    urduName: 'ایکسپورٹ بارکوڈ لیبل اسٹوڈیو',
    shortName: 'Barcode Studio',
    isMobileAppCore: false,
    category: 'business-export',
    categoryLabel: 'Business & Export',
    summary: 'Generate compliant thermal shipping labels and outer carton barcodes for surgical, leather & sports exports.',
    chatGptQuickPrompt: `Generate GS1-128 shipping carton specification for:
- Exporter: evonix Surgical Lab, Kolti Behram, Sialkot
- Consignee: Medtronic Global Distribution, Frankfurt, Germany
- Carton No: 12 of 80
- Content: Titanium Bone Drills SS316
- Barcode Format: GS1-128 (Application Identifiers: (01) GTIN-14, (10) Batch, (21) Serial)
Provide thermal print head configuration for 203 DPI Zebra / TSC printer.`,
    chatGptCustomGptInstructions: `You are the evonix Barcode and Thermal Printing Specialist. Output GS1-128 and Code128 string specifications with correct check digits and ZPL (Zebra Programming Language) printer code snippets.`,
    openApiSchema: {
      openapi: '3.1.0',
      info: { title: 'Barcode Studio API', version: '1.0.0' },
      paths: {
        '/barcode/generate-label': {
          post: {
            operationId: 'generateThermalLabel',
            summary: 'Generate 4x6 thermal barcode shipping label',
            requestBody: {
              required: true,
              content: { 'application/json': { schema: { type: 'object' } } },
            },
            responses: { '200': { description: 'Rendered label vector' } },
          },
        },
      },
    },
    geminiFunctionDeclaration: {
      name: 'generateBarcodeLabel',
      description: 'Generates compliant thermal barcode shipping labels in GS1-128 or Code 128 format.',
      parameters: {
        type: 'OBJECT',
        properties: {
          barcodeText: { type: 'STRING' },
          labelWidthMm: { type: 'NUMBER' },
          labelHeightMm: { type: 'NUMBER' },
          symbology: { type: 'STRING' },
        },
        required: ['barcodeText', 'symbology'],
      },
    },
    geminiSystemInstruction: `You are the Google AI Studio Gemini Industrial Barcode Architect for evonix. Validate barcode formats, calculate modulo 103 check digits, and generate ZPL thermal printer commands.`,
    geminiPromptTemplate: `Generate label format for barcode {{barcodeText}}, format {{symbology}}. Provide ZPL thermal printer code.`,
    githubWorkflowYaml: `name: Barcode Label Generation Check
on: [push]
jobs:
  test-barcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test GS1-128 generator
        run: echo "Testing GS1-128 check digit engine..."`,
    githubSchemaSpec: { title: 'BarcodeSpec', type: 'object' },
    cloudSamplePayload: {
      provider: 'evonix-cloud-sync',
      tool: 'export-barcode-studio',
      lastSynced: new Date().toISOString(),
      state: { labelType: '4x6-carton', symbology: 'GS1-128' },
    },
  },

  'live-repair-tracker': {
    toolId: 'live-repair-tracker',
    name: 'Live RMA Bench Repair Tracker',
    urduName: 'لائیو ریپئر ٹریکر',
    shortName: 'Live RMA Tracker',
    isMobileAppCore: false,
    category: 'diagnostics-lab',
    categoryLabel: 'Hardware Diagnostics',
    summary: 'Track motherboard micro-soldering progress, standby current readings, and 90-day warranty ticket status.',
    chatGptQuickPrompt: `Review live diagnostic status for laptop bench ticket #EVX-8821:
- Model: Dell Latitude 5420
- Initial Fault: Dead / No Power / 0.002A standby current draw
- Bench Diagnosis: Shorted ceramic filtering capacitor on 19V DC-in rail
- Post-Repair Test: Replaced with 25V 10uF ceramic cap, motherboard power sequences verified (3.3V, 5V, RAM 1.2V rails normal).
- Warranty: 90 days certified warranty

Summarize repair report for client with technician sign-off notes from evonix Kolti Behram lab.`,
    chatGptCustomGptInstructions: `You are the evonix Hardware Diagnostics Bench Engineer. Interpret bench power supply current readings, thermal hotspot data, and voltage rails to guide users through laptop repair status.`,
    openApiSchema: {
      openapi: '3.1.0',
      info: { title: 'Live Repair Tracker API', version: '1.0.0' },
      paths: {
        '/rma/status': {
          get: {
            operationId: 'getRepairStatus',
            summary: 'Fetch real-time bench repair status',
            responses: { '200': { description: 'RMA details' } },
          },
        },
      },
    },
    geminiFunctionDeclaration: {
      name: 'getTicketBenchStatus',
      description: 'Fetches real-time hardware diagnostics and repair status for an RMA ticket.',
      parameters: {
        type: 'OBJECT',
        properties: { ticketNumber: { type: 'STRING' } },
        required: ['ticketNumber'],
      },
    },
    geminiSystemInstruction: `You are the Google AI Studio Gemini Hardware Technician for evonix. Analyze schematic repair tickets, DC power draw, and micro-soldering steps.`,
    geminiPromptTemplate: `Summarize RMA ticket {{ticketNumber}} repair status and advise next diagnostic phase.`,
    githubWorkflowYaml: `name: Bench Ticket Webhook Sync
on: [workflow_dispatch]
jobs:
  sync-tickets:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Syncing bench tickets with repair ledger..."`,
    githubSchemaSpec: { title: 'RepairTicketSpec', type: 'object' },
    cloudSamplePayload: {
      provider: 'evonix-cloud-sync',
      tool: 'live-repair-tracker',
      lastSynced: new Date().toISOString(),
      state: { ticketId: 'EVX-8821', status: 'Passed Quality Control' },
    },
  },

  'printer-diagnostics': {
    toolId: 'printer-diagnostics',
    name: 'Thermal Receipt Printer Diagnostic Engine',
    urduName: 'پرنٹر ڈائیگنوسٹک انجن',
    shortName: 'Printer Diagnostics',
    isMobileAppCore: false,
    category: 'diagnostics-lab',
    categoryLabel: 'Hardware Diagnostics',
    summary: 'Interactive diagnostics for HP paper jams, torn fuser sleeves, and thermal receipt auto-cutter errors.',
    chatGptQuickPrompt: `Diagnose thermal receipt printer problem:
- Model: Xprinter XP-N160II / Epson TM-T20III
- Symptom: Cutter jammed halfway, red ERROR LED flashing 3 times, paper does not feed.
- Steps Taken: Power cycled, manual gear wheel turned.
Provide component-level repair procedure for technician at evonix Kolti Behram workshop.`,
    chatGptCustomGptInstructions: `You are the evonix Printer Hardware Specialist. Guide technicians through fuser teardown, thermal printhead impedance testing, and auto-cutter blade realignment.`,
    openApiSchema: {
      openapi: '3.1.0',
      info: { title: 'Printer Diagnostic API', version: '1.0.0' },
      paths: {
        '/printer/diagnose': {
          post: {
            operationId: 'diagnosePrinterFault',
            responses: { '200': { description: 'Diagnostic tree result' } },
          },
        },
      },
    },
    geminiFunctionDeclaration: {
      name: 'diagnosePrinterError',
      description: 'Troubleshoots laserjet and thermal receipt printer hardware faults.',
      parameters: {
        type: 'OBJECT',
        properties: {
          printerType: { type: 'STRING' },
          errorSymptom: { type: 'STRING' },
        },
        required: ['printerType', 'errorSymptom'],
      },
    },
    geminiSystemInstruction: `You are the Google AI Studio Gemini Printer Repair Specialist for evonix. Advise on gear train alignment, optical sensor cleaning, and thermal printhead maintenance.`,
    geminiPromptTemplate: `Diagnose {{printerType}} exhibiting {{errorSymptom}}. Provide step-by-step bench fix.`,
    githubWorkflowYaml: `name: Printer Troubleshooting Decision Tree
on: [push]
jobs:
  validate-tree:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Validating printer troubleshooting decision tree..."`,
    githubSchemaSpec: { title: 'PrinterDiagnosticSpec', type: 'object' },
    cloudSamplePayload: {
      provider: 'evonix-cloud-sync',
      tool: 'printer-diagnostics',
      lastSynced: new Date().toISOString(),
      state: { printerModel: 'ESC/POS 80mm', fault: 'Cutter Gear Jam' },
    },
  },

  'factory-network-tester': {
    toolId: 'factory-network-tester',
    name: 'Factory ERP & Customs Latency Benchmark',
    urduName: 'فیکٹری نیٹ ورک بینچ مارک',
    shortName: 'Network Latency Test',
    isMobileAppCore: false,
    category: 'diagnostics-lab',
    categoryLabel: 'Hardware Diagnostics',
    summary: 'Test factory premise latency bottlenecks, SQL database lag, and WeBOC customs gateway ping stability.',
    chatGptQuickPrompt: `Analyze industrial network latency log for export manufacturing plant in Sambrial/Sialkot:
- Primary WAN: Fiber Optics 50 Mbps (Latency to WeBOC Customs gateway: 142ms, Jitter: 34ms, Packet Loss: 4.2%)
- Secondary Backup WAN: Wireless PTCL PTP Link (Latency: 28ms, Jitter: 3ms, Packet Loss: 0%)
- Core Switch: Managed 24-Port Gigabit with VLAN for ERP server
Recommend Dual-WAN failover routing and MTU tuning to prevent ERP database transaction aborts.`,
    chatGptCustomGptInstructions: `You are the evonix Industrial Network Engineer. Diagnose enterprise packet loss, MTU fragmentation, and WeBOC customs gateway connection stability for industrial exporters.`,
    openApiSchema: {
      openapi: '3.1.0',
      info: { title: 'Factory Network Benchmark API', version: '1.0.0' },
      paths: {
        '/network/benchmark': {
          post: {
            operationId: 'benchmarkNetworkLatency',
            responses: { '200': { description: 'Network stability matrix' } },
          },
        },
      },
    },
    geminiFunctionDeclaration: {
      name: 'benchmarkFactoryNetwork',
      description: 'Benchmarks industrial premise network latency and gateway stability.',
      parameters: {
        type: 'OBJECT',
        properties: {
          pingMs: { type: 'NUMBER' },
          packetLossPercent: { type: 'NUMBER' },
          targetHost: { type: 'STRING' },
        },
        required: ['pingMs', 'targetHost'],
      },
    },
    geminiSystemInstruction: `You are the Google AI Studio Gemini Network Reliability Engineer for evonix. Optimize industrial factory WAN topologies, Mikrotik/Cisco router routing tables, and customs gateway pings.`,
    geminiPromptTemplate: `Benchmark network with Ping: {{pingMs}}ms, Loss: {{loss}}% to {{targetHost}}. Suggest failover and QoS rules.`,
    githubWorkflowYaml: `name: Network Latency Benchmark Monitor
on:
  schedule:
    - cron: '*/30 * * * *'
jobs:
  ping-monitor:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Monitoring customs gateway ping latency..."`,
    githubSchemaSpec: { title: 'NetworkBenchmarkSpec', type: 'object' },
    cloudSamplePayload: {
      provider: 'evonix-cloud-sync',
      tool: 'factory-network-tester',
      lastSynced: new Date().toISOString(),
      state: { pingAvg: 18, packetLoss: 0, status: 'Optimal' },
    },
  },
};

/**
 * The 5 Primary Mobile Web App Tools explicitly designated by the user:
 * 1. Global Micro-Invoice Generator (گلوبل مائیکرو انوائس جنریٹر)
 * 2. E-Commerce Margin & COD Simulator (ای کامرس بی ٹو بی مارجن کیلکولیٹر)
 * 3. B2B Industrial CBM & Freight Engine (بی ٹو بی انڈسٹریل CBM کارٹن و فریٹ کیلکولیٹر)
 * 4. Dedicated Developer Cost Calculator (ڈیڈیکیٹڈ ڈویلپر کاسٹ کیلکولیٹر)
 * 5. AI Visibility & E-E-A-T Checker (اے آئی اویلیبلٹی ای ای اے ٹی چیکر)
 */
export const CORE_5_MOBILE_TOOLS = Object.values(ALL_TOOL_INTEGRATIONS)
  .filter((t) => t.isMobileAppCore)
  .sort((a, b) => (a.mobileCoreOrder || 0) - (b.mobileCoreOrder || 0));
